-- MySQL Script generated by MySQL Workbench
-- 08/17/15 11:08:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`advert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`advert` (
  `idadvert` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `price` MEDIUMINT(11) NULL COMMENT '',
  `address` VARCHAR(255) NULL COMMENT '',
  `fk_agent` MEDIUMINT(11) NULL COMMENT '',
  `bedroom` SMALLINT(1) NULL COMMENT '',
  `livingroom` SMALLINT(1) NULL COMMENT '',
  `parking` SMALLINT(1) NULL COMMENT '',
  `kitchen` SMALLINT(1) NULL COMMENT '',
  `general_image` VARCHAR(200) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `location` VARCHAR(30) NULL COMMENT '',
  `hot` SMALLINT(1) NULL COMMENT '',
  `sold` SMALLINT(1) NULL COMMENT '',
  `type` VARCHAR(50) NULL COMMENT '',
  `recommend` SMALLINT(1) NULL COMMENT '',
  PRIMARY KEY (`idadvert`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscrible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscrible` (
  `idsubscrible` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(50) NULL COMMENT '',
  `date_subscribe` DATE NULL COMMENT '',
  PRIMARY KEY (`idsubscrible`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
